@echo off
echo Starting Eureka...
start "Eureka" cmd /k "cd eureka && mvnw.cmd spring-boot:run"
timeout /t 10
echo Starting Gateway...
start "Gateway" cmd /k "cd gateway && mvnw.cmd spring-boot:run"
echo Starting Auth Service...
start "Auth Service" cmd /k "cd auth-service && mvnw.cmd spring-boot:run"
echo Starting Medicine Service...
start "Medicine Service" cmd /k "cd medicine-service && mvnw.cmd spring-boot:run"
echo Starting Order Service...
start "Order Service" cmd /k "cd order-service && mvnw.cmd spring-boot:run"
echo All services started!
