server:
  port: ${PORT:8080}

spring:
  name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**
              filters:
                - RewritePath=/api/(?<segment>.*), /$\\{segment}

            - id: medicine-service
              uri: lb://MEDICINE-SERVICE
              predicates:
                - Path=/api/medicines/**
              filters:
                - RewritePath=/api/(?<segment>.*), /$\\{segment}

            - id: prescriptions-service
              uri: lb://MEDICINE-SERVICE
              predicates:
                - Path=/api/prescriptions/**

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/orders/**
              filters:
                - RewritePath=/api/(?<segment>.*), /$\\{segment}

            - id: management-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/management/**
              filters:
                - RewritePath=/api/(?<segment>.*), /$\\{segment}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
